version: '3.7'

services:
  gatsby:
    build: ./app
    depends_on:
      - strapi
    ports:
      - 8084:8000
      - 9929:9929
      - 9230:9230
    environment:
      GATSBY_WEBPACK_PUBLICPATH: /
      STRAPI_URL_SH: strapi:1337
      GATSBY_STRAPI_URL: http://strapi:1337
    command: ["./wait-for-strapi.sh"]
  strapi:
    build: ./api
    ports:
      - 1337:1337
    environment:
      NODE_ENV: development
    restart: always
